name: Setup node and pnpm
runs:
  using: "composite"
  steps:
    - uses: pnpm/action-setup@v4.1.0
    - uses: actions/setup-node@v5.0.0
      with:
        node-version-file: ".nvmrc"
    - run: pnpm install
      shell: bash
