name: CI workflow

on:
  pull_request:
  push:
    branches:
      - "main"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/pnpm

      - run: pnpm -r test:types
        if: always()
      - run: pnpm -r lint
        if: always()
      - run: pnpm -r test
        if: always()
      - run: pnpm -r build
        if: always()

  sherif:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - run: npx -y --package "sherif@$(node -p "require('./package.json')['devDependencies']['sherif']")" sherif

  knip:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/pnpm
      - run: pnpm knip
