name: CI workflow

on:
  pull_request:
  push:
    branches:
      - "main"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: ./.github/actions/pnpm

      - run: pnpm -r test:types
        if: always()
      - run: pnpm -r lint
        if: always()
      - run: pnpm -r test
        if: always()
      - run: pnpm -r build
        if: always()

  sherif:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - run: npx -y --package "sherif@$(node -p "require('./package.json')['devDependencies']['sherif']")" sherif

  knip:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: ./.github/actions/pnpm
      - run: pnpm knip

  prettier:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: ./.github/actions/pnpm
      - run: pnpm prettier --check .
